########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Projects, url: "/projects"}
    - { name: Publications, url: "/publications" }
    - { name: Team, url: "/teams" }
    - { name: Contact, url: "/contact" }


  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Projects, url: "/projects"}
    - { name: Publications, url: "/publications" }
    - { name: Team, url: "/teams" }
    - { name: Contact, url: "/contact" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/RedLogo.png"
# meta data
author: "Themefisher"
description: "This is meta description"
# google analitycs ID
google_analitycs_id: "" # your id
# contact form action
contact_form_action: "#" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2023 Designed and Developed by [COTS LABS](https://themefisher.com)"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:
  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "#"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "#"
